
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listDevices() : Promise<Result<DeviceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsGet() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsSet(key: string, value: string) : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsReset() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_reset") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async identity() : Promise<Result<IdentityDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoveredPeers() : Promise<Result<DiscoveredPeer[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discovered_peers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pendingPeers() : Promise<Result<PendingPeerDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pending_peers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectPeer(host: string, port: number, peerId: string | null) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_peer", { host, port, peerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async acceptPending(index: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("accept_pending", { index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async peerDevices(peerId: string) : Promise<Result<DeviceDescriptor[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("peer_devices", { peerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disconnect(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDeviceName(name: string) : Promise<Result<IdentityDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_device_name", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async snapshot() : Promise<Result<SessionSnapshot[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openSession(remotePeerId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_session", { remotePeerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openStream(sessionId: string, sourceDeviceId: string, sourceIsSystem: boolean, sinkPeerId: string, sinkDeviceId: string, bitrate: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_stream", { sessionId, sourceDeviceId, sourceIsSystem, sinkPeerId, sinkDeviceId, bitrate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeStream(sessionId: string, streamId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_stream", { sessionId, streamId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamControl(sessionId: string, streamId: number, action: string, value: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_control", { sessionId, streamId, action, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async muteAll() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mute_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disconnectAll() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrayState(state: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tray_state", { state }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async permissionStatus() : Promise<Permissions> {
    return await TAURI_INVOKE("permission_status");
},
async requestPermission(kind: string) : Promise<PermStatus> {
    return await TAURI_INVOKE("request_permission", { kind });
},
async setAutostart(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_autostart", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
incomingSession: IncomingSession,
peerDisconnected: PeerDisconnected,
peersChanged: PeersChanged,
statsTick: StatsTick
}>({
incomingSession: "incoming-session",
peerDisconnected: "peer-disconnected",
peersChanged: "peers-changed",
statsTick: "stats-tick"
})

/** user-defined constants **/



/** user-defined types **/

export type DeviceDescriptor = { id: string; name: string; kind: string }
export type DeviceInfo = { id: string; name: string; kind: DeviceKind; default_sample_rate: number; channels: number }
export type DeviceKind = "Input" | "Output" | "SystemAudio"
export type DiscoveredPeer = { peer_id: string; peer_name: string; host: string; port: number; version: string }
export type FecMode = "auto" | "always" | "never"
export type IdentityDto = { peer_id: string; peer_name: string }
export type IncomingSession = { peer_id: string; peer_name: string }
export type JitterMode = "auto" | "min" | { fixed: number }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
export type PeerDisconnected = { peer_id: string; reason: string }
export type PeersChanged = DiscoveredPeer[]
export type PendingPeerDto = { peer_id: string; peer_name: string; addr: string }
export type PermStatus = "granted" | "denied" | "prompt" | "not_applicable"
export type Permissions = { microphone: PermStatus; screen: PermStatus }
export type SessionSnapshot = { id: string; remote_peer_id: string; state: SessionState; streams: StreamSnapshot[] }
export type SessionState = "pending_outgoing" | "pending_incoming" | "active" | "closed"
export type Settings = { auto_accept_trusted: boolean; auto_start_with_system: boolean; default_bitrate: number; fec_mode: FecMode; fec_on_threshold_pct: number; fec_off_threshold_pct: number; fec_hysteresis_secs: number; jitter_mode: JitterMode; jitter_max_depth_ms: number; log_level: LogLevel; metrics_enabled: boolean; metrics_port: number; signaling_port: number }
export type StatsTick = StreamStat[]
export type StreamSnapshot = { id: number; state: StreamState; source_peer: string; sink_peer: string; udp_port: number; source_device: string; sink_device: string; volume: number; muted: boolean }
export type StreamStat = { session_id: string; stream_id: number; rtt_ms: number; loss_pct: number; kbps_sent: number; kbps_received: number }
export type StreamState = "negotiating" | "active" | "paused" | "error" | "closed"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
